apiVersion: apps/v1
kind: Deployment
metadata:
  name: rancher-ai-backend
  labels:
    app: rancher-ai-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rancher-ai-backend
  template:
    metadata:
      labels:
        app: rancher-ai-backend
    spec:
      containers:
        - name: backend
          image: jpgouin/rancher-ai-assistant-backend:latest 
          ports:
            - containerPort: 8000
          env:
            - name: OLLAMA_SERVER_URL
              value: http://open-webui-ollama.suseai.svc.cluster.local:11434
---
apiVersion: v1
kind: Service
metadata:
  name: rancher-ai-backend
spec:
  selector:
    app: rancher-ai-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: rancher-ai-backend-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    cert-manager.io/cluster-issuer: rancher-issuer
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - rancher-ai-assistant-backend.10.144.97.97.sslip.io         # <- Replace with your domain
      secretName: rancher-ai-backend-tls
  rules:
    - host: rancher-ai-assistant-backend.10.144.97.97.sslip.io       # <- Replace with your domain
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: rancher-ai-backend
                port:
                  number: 80
