apiVersion: apps/v1
kind: Deployment
metadata:
  name: rancher-ai-backend
  labels:
    app: rancher-ai-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rancher-ai-backend
  template:
    metadata:
      labels:
        app: rancher-ai-backend
    spec:
      containers:
        - name: backend
          image: jpgouin/rancher-ai-assistant-backend:0.1.0-rc8 
          ports:
            - containerPort: 8000

---
apiVersion: v1
kind: Service
metadata:
  name: rancher-ai-backend
spec:
  selector:
    app: rancher-ai-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
