apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "rancher-ai-assistant.fullname" . }}-mcpo
  labels:
    {{- include "rancher-ai-assistant.labels" . | nindent 4 }}
    app.kubernetes.io/component: mcpo
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "rancher-ai-assistant.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: mcpo
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "rancher-ai-assistant.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        app.kubernetes.io/component: mcpo
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "rancher-ai-assistant.serviceAccountName" . }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}-mcpo
          {{- with .Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: "{{ .Values.mcpo.image.repository }}:{{ .Values.mcpo.image.tag }}"
          imagePullPolicy: {{ .Values.mcpo.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          command: ["mcpo"] # Entrypoint of the container
          args: 
            - "--port"
            - "8000"
            - "--api-key"
            - "{ .Values.mcpo.key }}"
            - "--config"
            - "/etc/config/config.json"
          {{- with .Values.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.volumeMounts }}
          volumeMounts:
            - name: config-volume
              mountPath: /etc/config
          {{- end }}
      {{- with .Values.volumes }}
      volumes:
        - name: config-volume
          configMap:
            name: {{ include "rancher-ai-assistant.fullname" . }}-mcpo
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
