apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "rancher-ai-assistant.fullname" . }}-pvc
  labels:
    {{- include "rancher-ai-assistant.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.conversationsPvcSize }}
  storageClassName: {{ .Values.conversationsStorageClass | quote }}