apiVersion: v1
kind: Service
metadata:
  name: {{ include "rancher-ai-assistant.fullname" . }}-toolbox-rancher-pubapi
  labels:
    {{- include "rancher-ai-assistant.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "rancher-ai-assistant.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: toolbox-rancher-pubapi
