apiVersion: v1
kind: Service
metadata:
  name: rancher-ai-backend
  labels:
    {{- include "rancher-ai-assistant.labels" . | nindent 4 }}
    app.kubernetes.io/component: mcpo
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "rancher-ai-assistant.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: mcpo
